jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
on:
  push:
    branches:
    - main
    - release/*
on:
  pull_request:
    branches:
    - main
on:
  schedule:
  - cron: "0 2 * * 1-5"
